- project:
    templates:
      - openstack-python3-victoria-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tempest-integrated-networking
        - neutron-tempest-plugin-dynamic-routing
