- project:
    templates:
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
