- project:
    templates:
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
    check:
      jobs:
        - neutron-ovs-tempest-dvr
        - neutron-tempest-plugin-dynamic-routing:
            voting: false
    gate:
      jobs:
        - neutron-ovs-tempest-dvr
